// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aafhxtnnttonldxekpkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhZmh4dG5udHRvbmxkeGVrcGt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MTc4MzIsImV4cCI6MjA3MzM5MzgzMn0.dAunHz-i4J-PqgJxv3fMSMKX-A8wm_68oV6hH95KY04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});